<form method="post" action="edit">
    <p>Введите дату рождения:</p>
    <input type="date" name="birth"><br>
    <p>Опишите себя:</p>
    <textarea name="description" rows="10" cols="30"></textarea>
    <br>
    <br>
    <input type="submit" name="editSubmit">
</form>
<?php
if (!empty($object->data->errors)) {
    echo "<br>" . $object->data->errors . "<br>";
}
if (!empty($object->data->successful)) {
    echo "<br>" . $object->data->successful . "<br>";
}
?>
<br>
<br>
<a href="user">К профилю</a>
