<a href="edit" style="display:block;float: right">Редактировать профиль</a>
<br>
<a href="image" style="display:block;float: right">Загрузить аватар</a>
<br>
<a href="uploads" style="display:block;float: right">Загрузить изображение</a>
<br>
<a href="../index/index" style="display:block;float: right">К регистрации</a>
<form action="user" method="post" style="float: right;clear: both">
    <input type="submit" name="exit" value="Выйти">
</form>
Приветствую, <?php echo($_SESSION['logged_user']); ?> !!!
<br>
<br>
<h3>Ваш аватар:</h3>
<div style="width:300px;height:300px;background-size:cover;background-image:url(<?php echo "/" . $object->data->avatar ?>)">
</div>
<h3>О себе:</h3>
<p><?php echo $object->data->description ?></p>
<h3>Дата рождения:</h3>
<p><?php echo $object->data->birth ?></p>


