<form method="post" action="registration">
    <p>Введите имя:</p>
    <input type="text" name="name" placeholder="Имя"><br>
    <p>Введите пароль:</p>
    <input type="password" name="password" placeholder="Пароль"><br>
    <p>Введите email:</p>
    <input type="email" name="email" placeholder="email"><br>
    <?php
    if (!empty($object->data->errors)) {
        echo "<br>" . $object->data->errors . "<br>";
    }
    if (!empty($object->data->successful)) {
        echo "<br>" . $object->data->successful . "<br>";
    }
    ?>
    <br>
    <input type="submit" name="submit">
</form>
<a href="index">Назад</a>
